on:
  workflow_dispatch:
  schedule:
    # run every day at 23:00 UTC（bejing time 07:00）
    - cron: '0 23 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'

    - name: 7. setup python...
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: 8. send commit log to wework ...
      env:
        CORP_ID: ${{ secrets.CORP_ID }}
        CORP_SECRET: ${{ secrets.CORP_SECRET }}
        AGENT_ID: ${{ secrets.AGENT_ID }}

      run: |
        git log --since="1 hours ago" --pretty=format:"%ai %h %n%s%n" > commit_log.md

        python -m pip install requests

        python wechat_push.py
